export type {
    ProtectedRouteProps,
    RegisterBaseProps,
	RegisterPatient,
	MedicoRegistro,
	ApiResponse,
	LoginData,
	LoginResponse,
	UserResponse,
	DoctorList,
    PatientData,
	PatientsList,
	AfasiaTestConfig,
	PatientSessions,
    PatientContextType,
    Session,
    SessionContextType,
    PredefinedSessionTest,
    TestData,
    TestDescriptions,
    TestResult,
    TestResponse,
    InstancesRecords,
    SessionInstanceRecords,
    UserActivityContextType
} from './afasiaInterfaces';